version: '3.7'
services:
  poketbase: 
    image: pocketbase
    volumes:
      - type: volume
        source: 'data'
        target: '/pb_data'
    ports:
      - 8090:8090
    restart: unless-stopped
volumes: 
  data:
