version: "3.7"
services:
  # ---------------------------------------------------------------
  # Jellyfin
  # ---------------------------------------------------------------
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/New_York"
      JELLYFIN_PublishedServerUrl: "bwing.local"
    volumes:
      - type: bind
        source: "/home/bwing/volumes/jellyfin_config/_data"
        target: "/config"
      - type: bind
        source: "/mnt/media2/tv"
        target: "/data/tvshows"
      - type: bind
        source: "/mnt/media1/movies"
        target: "/data/movies"
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - internal
  # ---------------------------------------------------------------
  # Keycloak
  # ---------------------------------------------------------------
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - type: bind
        source: "/home/bwing/volumes/keycloak_postgresql_data/_data"
        target: "/bitnami/postgresql"
  keycloak:
    image: docker.io/bitnami/keycloak:21
    environment:
      - KEYCLOAK_ADMIN=bwing
      - KEYCLOAK_ADMIN_PASSWORD=replaceme12345
    depends_on:
      - postgresql
    ports:
      - "8686:8080"
    restart: unless-stopped
    networks:
      - internal
  # ---------------------------------------------------------------
  # Shield-DB
  # ---------------------------------------------------------------
  pocketbase:
    image: shield-pb:latest
    volumes:
      - type: volume
        source: "shield-db"
        target: "/pb/data"
    networks:
      - internal
    ports:
      - "8090:8090"
  # ---------------------------------------------------------------
  # Nginx
  # ---------------------------------------------------------------
  nginx:
    container_name: nginx
    image: nginx:1.18.0-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/bwing/volumes/nginx_ui/_data:/etc/nginx
networks:
  internal:
volumes:
  shield-db: