version: '3.7'
services:
  pocketbase:
    image: shield-pb:latest
    volumes:
      - pocketbase-data:/pb/data
    networks:
      - internal
    ports:
      - "8090:8090"
volumes:
  pocketbase-data:
networks:
  internal: