version: '3.7'
services:
  mongo:
    image: mongo:3.6
    container_name: ${COMPOSE_PROJECT_NAME}_mongo
    networks:
      - unifi
    restart: always
    volumes:
      - type: bind
        source: '/home/bwing/volumes/unifi_db/_data'
        target: '/data/db'
      - type: bind
        source: '/home/bwing/volumes/unifi_dbcfg/_data'
        target: '/data/configdb'
  controller:
    image: "jacobalberty/unifi:${TAG:-latest}"
    container_name: ${COMPOSE_PROJECT_NAME}_controller
    depends_on:
      - mongo
    networks:
      - unifi
    restart: always
    volumes:
      - type: bind
        source: '/home/bwing/volumes/unifi_dir/_data'
        target: '/unifi'
      - type: bind
        source: '/home/bwing/volumes/unifi_data/_data'
        target: '/unifi/data'
      - type: bind
        source: '/home/bwing/volumes/unifi_log/_data'
        target: '/unifi/log'
      - type: bind
        source: '/home/bwing/volumes/unifi_cert/_data'
        target: '/unifi/cert'
      - type: bind
        source: '/home/bwing/volumes/unifi_init/_data'
        target: '/unifi/init.d'
      - type: bind
        source: '/home/bwing/volumes/unifi_run/_data'
        target: '/var/run/unifi'
      - type: v
        source: '/home/bwing/volumes/unifi_backup'
        target: '/unifi/data/backup'
    user: unifi
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "9001:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" 
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
  logs:
    image: bash
    container_name: ${COMPOSE_PROJECT_NAME}_logs
    depends_on:
      - controller
    command: bash -c 'tail -F /unifi/log/*.log'
    restart: always
    volumes:
      - type: bind
        source: '/home/bwing/volumes/unifi_log/_data'
        target: '/unifi/log'
