{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "octoprint.fullname" . }}
  labels:
    {{- include "octoprint.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: >-
      {{ .Release.Namespace }}-{{ include "octoprint.fullname" . }}-addslash@kubernetescrd,{{ .Release.Namespace }}-{{ include "octoprint.fullname" . }}-stripprefix@kubernetescrd,{{ .Release.Namespace }}-{{ include "octoprint.fullname" . }}-headers@kubernetescrd
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "octoprint.fullname" . }}
                port:
                  name: http
{{- end }}
