apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.pgadmin.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
spec:
  type: {{ .Values.pgadmin.service.type }}
  selector:
    {{- include "postgres.pgadmin.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.pgadmin.service.port }}
      targetPort: http
      protocol: TCP
