{{- if or (not .Values.pgadmin.auth.existingSecret) (and .Values.pgadmin.oidc.enabled (not .Values.pgadmin.oidc.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.pgadmin.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
type: Opaque
stringData:
  {{- if not .Values.pgadmin.auth.existingSecret }}
  {{ .Values.pgadmin.auth.existingSecretKey | default "password" }}: {{ .Values.pgadmin.auth.password | quote }}
  {{- end }}
  {{- if and .Values.pgadmin.oidc.enabled (not .Values.pgadmin.oidc.existingSecret) }}
  {{ .Values.pgadmin.oidc.existingSecretKey | default "oauth2-client-secret" }}: {{ .Values.pgadmin.oidc.clientSecret | quote }}
  {{- end }}
{{- end }}
