{{- if not .Values.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.pg.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  {{ .Values.postgresql.auth.existingSecretKey | default "password" }}: {{ .Values.postgresql.auth.password | quote }}
{{- end }}
