version: '3.7'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  keycloak:
    image: docker.io/bitnami/keycloak:21
    environment:
      - KEYCLOAK_ADMIN=bwing
      - KEYCLOAK_ADMIN_PASSWORD=replaceme12345
    depends_on:
      - postgresql
    ports:
      - "8686:8080"
volumes:
  postgresql_data:
    driver: local