apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-secret
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
stringData:
  N8N_ENCRYPTION_KEY: {{ .Values.n8n.encryptionKey | quote }}
  {{- if .Values.n8n.basicAuth.enabled }}
  N8N_BASIC_AUTH_PASSWORD: {{ .Values.n8n.basicAuth.password | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  DB_POSTGRESDB_PASSWORD: {{ .Values.postgresql.password | quote }}
  {{- end }}
