{{- if .Values.compass.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.compass.fullname" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
    app.kubernetes.io/component: compass
spec:
  type: {{ .Values.compass.service.type }}
  selector:
    {{- include "mongodb.compass.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.compass.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
