{{- if and .Values.compass.enabled (or (not .Values.compass.oidc.existingSecret) (and .Values.compass.basicAuth.enabled (not .Values.compass.basicAuth.existingSecret))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.compass.fullname" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
    app.kubernetes.io/component: compass
type: Opaque
stringData:
  {{- if not .Values.compass.oidc.existingSecret }}
  {{ .Values.compass.oidc.existingSecretKey | default "oidc-client-secret" }}: {{ .Values.compass.oidc.clientSecret | quote }}
  {{ .Values.compass.oidc.sessionSecretKey | default "session-secret" }}: {{ .Values.compass.oidc.sessionSecret | quote }}
  {{- end }}
  {{- if and .Values.compass.basicAuth.enabled (not .Values.compass.basicAuth.existingSecret) }}
  {{ .Values.compass.basicAuth.existingSecretKey | default "basicauth-password" }}: {{ .Values.compass.basicAuth.password | quote }}
  {{- end }}
{{- end }}
