apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.mongo.fullname" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: {{ .Values.mongodb.service.type }}
  selector:
    {{- include "mongodb.mongo.selectorLabels" . | nindent 4 }}
  ports:
    - name: mongodb
      port: {{ .Values.mongodb.service.port }}
      targetPort: mongodb
      protocol: TCP
