{{- if not .Values.mongodb.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.mongo.fullname" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
type: Opaque
stringData:
  {{ .Values.mongodb.auth.existingSecretKey | default "password" }}: {{ .Values.mongodb.auth.password | quote }}
{{- end }}
